function handles = guiTextAxes(hObject,strings)
% This function is for internal use by the interactive demo
% programs that accompany the text
%    "Signals and Systems: A MATLAB-Integrated Approach"
%    by Oktay Alkin.
% Copyright (c) 2014 by Oktay Alkin.
% All rights reserved.
%
  tmpPan = uipanel('Parent',hObject,...
    'BorderType','none',...
    'BackgroundColor',guiBgColor);
  axesText = axes('Parent',tmpPan,...
     'Position',[0,0,1,1],...
     'Box','off',...
     'Visible','off',...
     'Units','normalized',...
     'Clipping','on');
  handles = cell(1,1+max(size(strings)));
  handles{1} = axesText;
  axes(axesText);
  for i = 1:max(size(strings))
    tmpCell = strings{i};
    tmpPos = tmpCell{1};
    tmpStr = tmpCell{2};
    hTxt = text(tmpPos(1),tmpPos(2),...
      sprintf('\\textsf{%s}',tmpStr),...
      'Interpreter','latex',...
      'FontSize',guiFontSize,...
      'HorizontalAlignment','left',...
      'VerticalAlignment','baseline');
    handles{i+1} = hTxt;
  end; 
end  